[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]

[build]
  command = "bun run build"
  publish = "dist"

# HTTP to HTTPS redirect
[[redirects]]
  from = "http://공룡페이.com/*"
  to = "https://www.공룡페이.com/:splat"
  status = 301
  force = true

# Non-www to www redirect
[[redirects]]
  from = "https://공룡페이.com/*"
  to = "https://www.공룡페이.com/:splat"
  status = 301
  force = true

# SPA fallback (must be last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
