# .github/workflows/deploy.yml

name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# 워크플로우가 gh-pages 브랜치에 쓸 수 있도록 권한을 설정합니다.
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. main 브랜치의 최신 코드를 가져옵니다.
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Bun(자바스크립트 실행도구)을 설치합니다.
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # 3. 웹사이트에 필요한 라이브러리들을 설치합니다.
      - name: Install dependencies
        run: bun install

      # 4. 웹사이트를 빌드하여 'dist' 폴더에 결과물을 생성합니다.
      - name: Build project
        run: bun run build
      
      # 5. 빌드된 결과물을 gh-pages 브랜치에 배포합니다.
      # 이 액션은 gh-pages 브랜치가 없으면 새로 만들고,
      # 기존에 있던 내용은 완전히 새로운 내용으로 덮어씁니다.
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: xn--ob0b39t2wlgzl.com
